### ISSUE TITLE
PCOInvalidModelError

### ISSUE THREAD

**Issue by pastorhudson** [billdeitrick/pypco#25]
I'm not able to create a Form Field after creating a Form.
Here's the code:
```
import pypco
import os

pco = pypco.PCO(os.environ.get('PCO_CLIENT_ID'),
                os.environ.get('PCO_CLIENT_SECRET'))
new_form = pco.new(pypco.models.people.Form)
new_form.name = 'Test'
new_form.description = "Test description"
new_form.create()
print(f"Created new form with id: {new_form.id}")
pco_field = pco.new(pypco.models.people.FormField)
print(f"pco_field.type: {pco_field.type}")
pco_field.field_type = "phone_number"
pco_field.label = "Phone Number"
pco_field.required = False
pco_field.sequence = 0
print(f"pco_field._data: {pco_field._data}")
print(f"new_form._data: {new_form._data}")
new_form.rel.fields.add(pco_field)
new_form.update()
```
And here's the output:
```
/home/rhudson/PycharmProjects/pcochef/venv/bin/python /home/rhudson/.PyCharm2019.3/config/scratches/scratch.py
Created new form with id: 91302
pco_field.type: FormField
pco_field._data: {'type': 'FormField', 'attributes': {'field_type': 'phone_number', 'label': 'Phone Number', 'required': False, 'sequence': 0}}
new_form._data: {'type': 'Form', 'id': '91302', 'attributes': {'active': None, 'created_at': '2020-01-01T20:02:17Z', 'deleted_at': None, 'description': 'Test description', 'name': 'Test', 'public_url': 'https://churchcenter.com/people/forms/91302', 'submission_count': 0, 'updated_at': '2020-01-01T20:02:17Z'}, 'links': {'fields': 'https://api.planningcenteronline.com/people/v2/forms/91302/fields', 'form_submissions': 'https://api.planningcenteronline.com/people/v2/forms/91302/form_submissions', 'self': 'https://api.planningcenteronline.com/people/v2/forms/91302'}}
Traceback (most recent call last):
  File "/home/rhudson/.PyCharm2019.3/config/scratches/scratch.py", line 19, in <module>
    new_form.rel.fields.add(pco_field)
  File "/home/rhudson/PycharmProjects/pcochef/venv/lib/python3.8/site-packages/pypco/models/base_model.py", line 419, in add
    raise PCOInvalidModelError("The model is missing the \"type\" or \"id\" attribute and cannot be created.")
pypco.models.base_model.PCOInvalidModelError: The model is missing the "type" or "id" attribute and cannot be created.

Process finished with exit code 1
```
As best I can tell FormField is the correct model, 'fields' is the correct relationship. I just can't figure out why it doesn't work.

**Comment by pastorhudson** [comment]
I just figured it out: I had to use create instead of add. I was using the example of the addresses in the code documentation. 
new_form.rel.fields.create(pco_field)
